### ISSUE TITLE
How to run on MacOS?

### ISSUE THREAD

**Issue by MichaelJGW** [mviereck/dockerfile-x11docker-cinnamon#1]
I'm getting this error 

```
error: Cannot autolaunch D-Bus without X11 $DISPLAY
Usage:
  dconf write KEY VALUE 
Write a new value to a key
Arguments:
  KEY         A key path (starting, but not ending with '/')
  VALUE       The value to write (in GVariant format)
error: Cannot autolaunch D-Bus without X11 $DISPLAY
Usage:
  dconf write KEY VALUE 
Write a new value to a key
Arguments:
  KEY         A key path (starting, but not ending with '/')
  VALUE       The value to write (in GVariant format)

```

I was following this article to install X11 but I'm still getting the same error 
https://blog.alexellis.io/linux-desktop-on-mac/

**Comment by mviereck** [comment]
I don't have a mac so I cannot check myself.
The dconf error message is harmless. dconf is only used to set a background wallpaper for the desktop.

cinnamon needs a running dbus system daemon in container. x11docker can set that up, but there is no x11docker fork for mac.

You can try something like this:
```
FROM x11docker/cinnamon

RUN echo '#! /bin/sh\n\
dbus-daemon --system --fork \n\
dbus-launch $* \n\
' > /usr/local/bin/start 
RUN chmod +x /usr/local/bin/start 

ENTRYPOINT ["/usr/local/bin/start"]
CMD ["cinnamon-session"]
```
This would run a dbus system daemon, but cinnamon as root user. If this setup works so far, we could look for possibilities to run cinnamon as an unprivileged user.

**Comment by mviereck** [comment]
Sorry, there has been an issue with `ENTRYPOINT` in image and in example. It is fixed now and I have edited my answer above. Please try again.
